steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}', '.' ]
images:
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}'
substitutions:
  _REGION: europe-southwest1
  _REPO_NAME: public
  _IMAGE_NAME: license-checker